'use strict';

/**
 * Catálogo versionado de señales físicas de Bottle Lab Pro — contrato:
 * bottle-lab-pro.signals.v1
 *
 * Cada señal documenta qué puede indicar Y qué NO demuestra por separado, a propósito: es la
 * defensa editorial explícita contra convertir una asociación regional o funcional débil en
 * una regla. `signal_type` en `bank/items.js` referencia el `code` de este catálogo.
 */

const SIGNALS = Object.freeze([
  {
    code: 'shape',
    objective_description: 'Perfil general de la botella (bordelesa, borgoñona, alsaciana, flauta, etc.), fijado por el molde de fabricación.',
    what_it_can_indicate: 'Tradición estética o de estilo asociada históricamente a esa forma en algunas regiones.',
    what_it_does_not_prove: 'Variedad, origen ni calidad -- las formas se fabrican y usan globalmente sin restricción legal general.',
    strength: 'weak',
    modifying_contexts: ['Solo gana fuerza si se cruza con una región/denominación ya confirmada por otra fuente (p. ej. una etiqueta).'],
    exceptions: ['Algunas formas están ligadas a normativas de denominación muy específicas (poco frecuente); verificar caso por caso, nunca asumir por defecto.'],
    associated_misconceptions: ['bottle.shape_equals_origin', 'bottle.shape_equals_variety'],
    technical_function: 'Ninguna función técnica intrínseca más allá de contener el líquido; los hombros pueden tener una función menor (ver "shoulders").',
    overinference_risk: 'Alto -- es la señal más comúnmente sobre-interpretada como prueba de variedad u origen.',
  },
  {
    code: 'glass_color',
    objective_description: 'Tono del vidrio: transparente, verde, ámbar o muy oscuro.',
    what_it_can_indicate: 'Nivel de protección contra la luz UV que el productor eligió dar al vino.',
    what_it_does_not_prove: 'Edad del vino, calidad ni estilo -- es una decisión tomada al fabricar la botella, no un efecto acumulado por el tiempo.',
    strength: 'weak',
    modifying_contexts: ['El vidrio transparente es la norma esperada en rosados y muchos blancos jóvenes -- no es una anomalía que requiera explicación.'],
    exceptions: ['Algunos vinos naturales/orgánicos usan vidrio claro deliberadamente pese a mayor exposición UV, como declaración de estilo.'],
    associated_misconceptions: ['bottle.dark_glass_equals_old'],
    technical_function: 'Filtra luz UV, retardando reacciones fotoquímicas indeseadas ("luz golpeada").',
    overinference_risk: 'Medio -- confundir protección UV con maduración o añada real.',
  },
  {
    code: 'glass_thickness',
    objective_description: 'Espesor de la pared de vidrio, perceptible al tacto o por comparación visual.',
    what_it_can_indicate: 'En espumantes, un espesor mínimo funcional necesario para resistir la presión interna embotellada.',
    what_it_does_not_prove: 'Calidad del vino en ningún caso; en vinos tranquilos no cumple ninguna función más allá de la presentación.',
    strength: 'non_diagnostic',
    modifying_contexts: ['Solo es relevante como señal funcional en la categoría espumante; en vino tranquilo es puramente estético.'],
    exceptions: [],
    associated_misconceptions: ['bottle.weight_equals_quality'],
    technical_function: 'En espumantes: resistencia estructural a la presión interna (típicamente desde 6 bar).',
    overinference_risk: 'Alto -- fácil de confundir con "peso" general y de sobreinterpretar como inversión en calidad.',
  },
  {
    code: 'glass_weight',
    objective_description: 'Peso total de la botella vacía, percibido al sostenerla.',
    what_it_can_indicate: 'Nivel de inversión del productor en la presentación; en espumantes, cumplimiento del mínimo estructural funcional.',
    what_it_does_not_prove: 'Calidad, precio real de mercado ni cuidado enológico -- el peso por encima del mínimo funcional es una decisión de packaging desacoplada del contenido.',
    strength: 'non_diagnostic',
    modifying_contexts: ['En espumantes, un peso claramente por debajo del rango típico sí sería una alerta funcional real -- pero un peso alto nunca es señal positiva de calidad.'],
    exceptions: [],
    associated_misconceptions: ['bottle.weight_equals_quality'],
    technical_function: null,
    overinference_risk: 'Muy alto -- es la misconception central y más extendida del dominio.',
  },
  {
    code: 'punt',
    objective_description: 'Fondo cóncavo (hacia adentro) de la botella, de profundidad variable.',
    what_it_can_indicate: 'Convención de manufactura y, en espumantes de método tradicional, cierta función estructural adicional.',
    what_it_does_not_prove: 'Calidad, precio ni autenticidad de método -- hoy es mayormente estético incluso en categorías donde tuvo origen funcional.',
    strength: 'weak',
    modifying_contexts: ['Gana fuerza (a "moderate") solo si se combina con otras señales de espumante, como el alambre y el morrión.'],
    exceptions: ['Un punt profundo en un tinto de mesa corriente no tiene ninguna base funcional -- es puramente estético.'],
    associated_misconceptions: ['bottle.punt_equals_quality'],
    technical_function: 'En espumantes de método tradicional: cierta resistencia estructural adicional, hoy no indispensable con el vidrio moderno.',
    overinference_risk: 'Muy alto -- segunda misconception más extendida del dominio, después del peso.',
  },
  {
    code: 'shoulders',
    objective_description: 'Forma de los hombros de la botella: altos y rectos vs. inclinados y redondeados.',
    what_it_can_indicate: 'Familia estética asociada débilmente a ciertas tradiciones varietales o regionales.',
    what_it_does_not_prove: 'Variedad exacta.',
    strength: 'weak',
    modifying_contexts: [],
    exceptions: [],
    associated_misconceptions: ['bottle.shape_equals_variety'],
    technical_function: 'Los hombros altos históricamente ayudaban a retener el sedimento al servir en tintos de guarda con crianza prolongada.',
    overinference_risk: 'Medio.',
  },
  {
    code: 'height_proportion',
    objective_description: 'Altura y proporción general de la botella respecto a su base.',
    what_it_can_indicate: 'Familia estética o de posicionamiento de mercado (formatos boutique, premium, económicos).',
    what_it_does_not_prove: 'Calidad intrínseca del contenido.',
    strength: 'non_diagnostic',
    modifying_contexts: [],
    exceptions: [],
    associated_misconceptions: ['bottle.expensive_packaging_equals_quality'],
    technical_function: null,
    overinference_risk: 'Bajo -- rara vez se sobreinterpreta sola, pero suma al efecto acumulado de presentación.',
  },
  {
    code: 'closure_cork',
    objective_description: 'Cierre de corcho natural (o aglomerado/técnico) visible bajo la cápsula.',
    what_it_can_indicate: 'Elección del productor que permite cierto grado de micro-oxigenación durante la guarda.',
    what_it_does_not_prove: 'Calidad, precio ni potencial de guarda por sí solo -- depende de la categoría y tradición regional del vino.',
    strength: 'weak',
    modifying_contexts: ['Solo es relevante como indicio de guarda si se combina con otra evidencia de vocación de guarda ya declarada.'],
    exceptions: ['Existen corchos técnicos/aglomerados que imitan la apariencia del corcho natural sin la misma función de micro-oxigenación.'],
    associated_misconceptions: ['bottle.cork_equals_quality'],
    technical_function: 'Permite micro-oxigenación controlada durante la crianza en botella; riesgo conocido de TCA ("corcho").',
    overinference_risk: 'Muy alto -- misconception cultural profundamente arraigada.',
  },
  {
    code: 'closure_screwcap',
    objective_description: 'Cierre de rosca (tipo Stelvin) en lugar de corcho.',
    what_it_can_indicate: 'Elección técnica orientada a preservar frescura y carácter frutal, especialmente en blancos y tintos jóvenes.',
    what_it_does_not_prove: 'Precio ni categoría -- se usa en vinos de alta gama en varias tradiciones regionales (Australia, Nueva Zelanda, entre otras).',
    strength: 'non_diagnostic',
    modifying_contexts: ['En regiones/tradiciones donde la rosca es el estándar (declarado en otra fuente, no en la botella), no es evidencia de nada respecto al precio.'],
    exceptions: [],
    associated_misconceptions: ['bottle.screwcap_equals_cheap'],
    technical_function: 'Elimina el riesgo de TCA; controla con precisión el intercambio de oxígeno (prácticamente nulo).',
    overinference_risk: 'Muy alto -- es el espejo exacto de la misconception del corcho.',
  },
  {
    code: 'closure_crown',
    objective_description: 'Cierre tipo corona (chapa metálica, como en cerveza), poco frecuente en vino terminado.',
    what_it_can_indicate: 'En espumantes, suele señalar una fase intermedia del proceso (segunda fermentación en botella antes del degüelle), no necesariamente el cierre comercial final.',
    what_it_does_not_prove: 'Calidad final del producto ya embotellado y comercializado.',
    strength: 'moderate',
    modifying_contexts: ['Solo diagnóstica en contexto técnico de proceso; si aparece en el producto final comercializado, es una elección deliberada poco común.'],
    exceptions: [],
    associated_misconceptions: [],
    technical_function: 'Sello hermético económico y fiable, estándar en la fase de segunda fermentación de muchos espumantes de método tradicional antes del degüelle.',
    overinference_risk: 'Bajo -- señal poco frecuente y generalmente mal comprendida por desconocimiento, no por sesgo activo.',
  },
  {
    code: 'capsule',
    objective_description: 'Material y acabado de la cápsula que cubre el cierre (estaño, plástico termorretráctil, cera, etc.).',
    what_it_can_indicate: 'Nivel de inversión en presentación del productor.',
    what_it_does_not_prove: 'Calidad del contenido.',
    strength: 'non_diagnostic',
    modifying_contexts: [],
    exceptions: [],
    associated_misconceptions: ['bottle.expensive_packaging_equals_quality'],
    technical_function: 'Protección física menor del cierre durante transporte/almacenamiento; sin función enológica directa.',
    overinference_risk: 'Medio.',
  },
  {
    code: 'embossing',
    objective_description: 'Relieve o gofrado en el vidrio (logotipos, escudos, texturas).',
    what_it_can_indicate: 'Inversión en identidad de marca y diferenciación visual.',
    what_it_does_not_prove: 'Origen, calidad ni escala de producción.',
    strength: 'non_diagnostic',
    modifying_contexts: [],
    exceptions: [],
    associated_misconceptions: ['bottle.expensive_packaging_equals_quality'],
    technical_function: null,
    overinference_risk: 'Medio.',
  },
  {
    code: 'fill_level',
    objective_description: 'Nivel del vino respecto al cierre (ullage), visible por transparencia o estimado.',
    what_it_can_indicate: 'Indicio de condición de conservación o de tiempo transcurrido en botella.',
    what_it_does_not_prove: 'Por sí solo, un nivel bajo NO prueba defecto -- el umbral esperado cambia según la edad declarada y el tipo de cierre.',
    strength: 'moderate',
    modifying_contexts: ['El umbral "normal" de ullage sube con los años de guarda declarados; un nivel que sería alarmante en un vino joven es esperable en uno de 20 años.'],
    exceptions: ['Los cierres de rosca tienden a mostrar menos variación de nivel que el corcho, independientemente de la edad.'],
    associated_misconceptions: ['bottle.low_fill_equals_fault'],
    technical_function: 'Indicador indirecto de la integridad del sellado a lo largo del tiempo.',
    overinference_risk: 'Alto -- se trata como prueba absoluta de defecto sin ajustar por la edad esperada.',
  },
  {
    code: 'physical_condition',
    objective_description: 'Estado general de la etiqueta, el vidrio y sedimentos visibles.',
    what_it_can_indicate: 'Historial de almacenamiento y manipulación de esa botella concreta.',
    what_it_does_not_prove: 'Calidad del vino en el momento de embotellado.',
    strength: 'weak',
    modifying_contexts: ['Sedimento visible es normal y esperable en tintos de guarda -- no es un defecto.'],
    exceptions: [],
    associated_misconceptions: [],
    technical_function: null,
    overinference_risk: 'Medio -- confundir sedimento normal con defecto.',
  },
  {
    code: 'graphic_design',
    objective_description: 'Estilo gráfico de la etiqueta y presentación general (minimalista, clásico, artesanal, etc.).',
    what_it_can_indicate: 'Segmento de mercado objetivo y estrategia de posicionamiento de marca.',
    what_it_does_not_prove: 'Calidad intrínseca ni método de producción -- el minimalismo y el diseño "clásico" son modas de diseño replicables por cualquier productor.',
    strength: 'non_diagnostic',
    modifying_contexts: [],
    exceptions: [],
    associated_misconceptions: ['bottle.minimal_design_equals_premium'],
    technical_function: null,
    overinference_risk: 'Alto -- exactamente el mecanismo que el marketing de vino explota deliberadamente.',
  },
  {
    code: 'special_format',
    objective_description: 'Formato no estándar (media botella, magnum, doble magnum, etc.).',
    what_it_can_indicate: 'Relación superficie/volumen distinta, que afecta la velocidad de evolución del vino SI éste está destinado a guarda.',
    what_it_does_not_prove: 'Que la conservación sea "mejor" en cualquier contexto -- solo es relevante si el vino en cuestión está pensado para envejecer.',
    strength: 'moderate',
    modifying_contexts: ['Solo relevante para la inferencia de evolución si hay evidencia adicional de vocación de guarda; no aporta nada sobre calidad por sí mismo.'],
    exceptions: ['Un magnum de un vino de consumo inmediato no se beneficia de forma relevante del formato.'],
    associated_misconceptions: ['bottle.large_format_always_better'],
    technical_function: 'Menor relación superficie/volumen ⇒ evolución más lenta y homogénea durante la guarda.',
    overinference_risk: 'Medio -- se generaliza sin condición de aplicación.',
  },
  {
    code: 'wire_cage',
    objective_description: 'Alambre y morrión (bozal) que asegura el cierre, típico de espumantes.',
    what_it_can_indicate: 'Confirma que hay presión interna significativa embotellada.',
    what_it_does_not_prove: 'Método de elaboración exacto, tiempo de crianza ni calidad.',
    strength: 'determinative',
    modifying_contexts: [],
    exceptions: [],
    associated_misconceptions: [],
    technical_function: 'Retiene mecánicamente el cierre contra la presión interna (habitualmente desde 3-6 bar).',
    overinference_risk: 'Bajo para la inferencia de presión (es genuinamente determinativa); alto si se extiende a inferir método o calidad.',
  },
  {
    code: 'functional_signal',
    objective_description: 'Categoría general para rasgos de diseño con una función técnica real no cubierta por las señales anteriores (p. ej. anillo antigoteo, cuello reforzado, base antideslizante).',
    what_it_can_indicate: 'Una decisión de ingeniería de envase con un propósito práctico verificable.',
    what_it_does_not_prove: 'Calidad del vino -- una función técnica real no es evidencia de calidad, solo de utilidad práctica del envase.',
    strength: 'weak',
    modifying_contexts: ['La fuerza depende del rasgo específico -- cada ítem debe documentar la función exacta en su propio campo technical_function, nunca dejarla genérica.'],
    exceptions: [],
    associated_misconceptions: [],
    technical_function: 'Variable según el rasgo específico -- debe documentarse en cada ítem que use esta señal.',
    overinference_risk: 'Medio -- el riesgo real es tratar "tiene función técnica" como sinónimo de "indica calidad".',
  },
  {
    code: 'marketing_signal',
    objective_description: 'Categoría general para elementos cuyo propósito primario es comunicar una idea comercial (texto de contraetiqueta, sellos decorativos no oficiales, menciones de tradición o premios no verificables desde la botella).',
    what_it_can_indicate: 'La estrategia de posicionamiento e intención comunicativa del productor.',
    what_it_does_not_prove: 'Ningún hecho verificable sobre el vino -- ninguna conclusión de calidad debe apoyarse únicamente en una señal de este tipo.',
    strength: 'non_diagnostic',
    modifying_contexts: [],
    exceptions: [],
    associated_misconceptions: ['bottle.expensive_packaging_equals_quality'],
    technical_function: null,
    overinference_risk: 'Muy alto -- es, por diseño, la señal más persuasiva y menos informativa de todo el envase.',
  },
]);

const SIGNALS_BY_CODE = Object.freeze(Object.fromEntries(SIGNALS.map((s) => [s.code, s])));

function getSignal(code) {
  return SIGNALS_BY_CODE[code] || null;
}

module.exports = { SIGNALS, SIGNALS_BY_CODE, getSignal };
