// Generated by tools/question_generation/distinction_coach_exporter.py
// Compiled from knowledge/ assessment-intelligence assets. Do not edit.
// Formative guidance only. safe_for_examiner=false.
window.DISTINCTION_COACH = {
  "command_verbs": {
    "assess": {
      "definition": "Make an informed judgement about the value, quality, or significance of something, based on stated criteria.",
      "do": [
        "State a clear judgement",
        "Support with specific tasting or regional evidence",
        "Use appropriate WSET criteria"
      ],
      "do_not": [
        "Give unsupported opinion",
        "List observations without a conclusion"
      ],
      "mentor_hint": "Lead with your judgement ('This wine is of outstanding quality'), then immediately provide 3 or more specific observations that support it. Do not build up to the conclusion."
    },
    "compare": {
      "definition": "Identify similarities and differences between two or more items. Both similarities AND differences are expected unless otherwise stated.",
      "do": [
        "Address both similarities and differences",
        "Use parallel structure for clarity",
        "Cover multiple dimensions"
      ],
      "do_not": [
        "Describe each item separately without linking them",
        "Cover only one item in detail"
      ],
      "mentor_hint": "Organise by dimension: 'In terms of climate, X is [cool/warm] whereas Y is [cool/warm]...' — do not write an essay on X then an essay on Y."
    },
    "describe": {
      "definition": "State the characteristics, features, or appearance of something. Do not explain causes or reasons.",
      "do": [
        "Name features",
        "Use SAT vocabulary (for tasting questions)",
        "Be specific",
        "Cover all relevant dimensions"
      ],
      "do_not": [
        "Explain why",
        "Give opinions",
        "Compare to other examples",
        "Add causes or mechanisms"
      ],
      "mentor_hint": "Answer 'what' questions only. If you catch yourself writing 'because' or 'this means', you are explaining, not describing."
    },
    "evaluate": {
      "definition": "Make a substantiated judgement, weighing the significance of evidence. Often implies a broader or more nuanced consideration than 'assess'.",
      "do": [
        "Weigh multiple pieces of evidence",
        "State a clear conclusion",
        "Acknowledge complexity where relevant"
      ],
      "do_not": [
        "Simply list facts (that is describing)",
        "Give opinion without evidence"
      ],
      "mentor_hint": "Think of 'evaluate' as 'explain + judge': explain the key factors, then state which you consider most significant and why."
    },
    "explain": {
      "definition": "Give reasons for, or account for, a fact, phenomenon, or outcome. Must include a cause-and-effect relationship.",
      "do": [
        "State the cause",
        "State the mechanism or process",
        "State the outcome or effect",
        "Use WSET technical vocabulary"
      ],
      "do_not": [
        "Merely name or list (that is describing, not explaining)",
        "Give unsupported assertions"
      ],
      "mentor_hint": "Use the structure: [Factor] → [mechanism] → [result in the wine]. For example: 'Cool temperatures slow ripening → less sugar accumulation, more malic acid retained → higher acidity in finished wine.'"
    },
    "justify": {
      "definition": "Give reasons or evidence in support of a stated position or choice. The position is given; you must defend it.",
      "do": [
        "Select the strongest, most specific supporting evidence",
        "Link evidence directly to the position",
        "Use WSET vocabulary"
      ],
      "do_not": [
        "Argue against the position",
        "Give generic descriptions unrelated to the claim"
      ],
      "mentor_hint": "Start by restating the position in one line, then give 3+ specific reasons. Each reason should connect directly to the claim."
    }
  },
  "common_quality_errors": [
    "Selecting 'excelente' for a simple wine because it is personally enjoyed",
    "Not recognising 'simple' as a valid and mark-earning descriptor for basic wines",
    "Selecting 'muy bueno' for a wine with only primary aromas (should be 'bueno' or 'aceptable')",
    "Selecting 'bueno' when wine clearly shows all three aroma categories and long finish (should be 'muy bueno' or 'excelente')"
  ],
  "governance": {
    "examiner_scoring_allowed": false,
    "formative_only": true,
    "safe_for_examiner": false,
    "uses_api": false,
    "uses_llm": false
  },
  "justification_connectors": [
    "porque",
    "ya que",
    "debido",
    "por lo tanto",
    "esto indica",
    "se debe a",
    "lo que sugiere"
  ],
  "mentor_hints": {
    "MCQ_strategy": {
      "common_errors": [
        "Overthinking distractors",
        "Selecting partially correct answers"
      ],
      "hint": "For MCQ, eliminate clearly wrong options first. The correct answer will be fully accurate, not partially. WSET uses precise vocabulary — 'dry' is not the same as 'off-dry'."
    },
    "SAT_appearance": {
      "common_errors": [
        "Forgetting to assess clarity",
        "Using non-SAT vocabulary (e.g. 'pretty', 'dark')"
      ],
      "hint": "Work through Appearance in order: clarity → intensity → colour. Each element has its own scale. Colour must match the wine type (white, rosé, red)."
    },
    "SAT_nose": {
      "common_errors": [
        "Mixing primary/secondary/tertiary without assigning categories",
        "Listing generic 'fruit' without specifics"
      ],
      "hint": "After stating condition (clean/faulty) and intensity, identify aromas by category: primary (fruit, floral, vegetal), secondary (oak, MLF, yeast), tertiary (bottle ageing, oxidation). At least one specific descriptor per category earns the mark."
    },
    "SAT_palate": {
      "common_errors": [
        "Omitting acidity or tannin assessment",
        "Treating 'body' as a flavour rather than a structural element",
        "Confusing finish length scales"
      ],
      "hint": "For palate, cover all nine elements in order: sweetness, acidity, tannin (red only), alcohol, body, flavour intensity, flavour characteristics, finish. Body and finish are structural conclusions, not flavours."
    },
    "SAT_quality": {
      "common_errors": [
        "Selecting quality level without justification from tasting notes",
        "Using 'excelente' for wines with no tertiary complexity"
      ],
      "hint": "Quality level must be consistent with your tasting notes. Outstanding requires: pronounced intensity + all three aroma categories + balance + long finish. Simple wines cannot be outstanding."
    },
    "SAT_readiness": {
      "common_errors": [
        "Mismatching readiness with development stage",
        "Selecting 'demasiado joven' for a developing wine"
      ],
      "hint": "'Can drink now but has potential' is the correct answer for most premium wines with developing complexity. Only select 'too young' if the wine is clearly unresolved (high unintegrated tannin, no development)."
    },
    "short_answer_structure": {
      "common_errors": [
        "Giving only one reason for a multi-mark question",
        "Explaining without specifying the cause"
      ],
      "hint": "Count the marks. A 4-mark explain question needs 4 distinct causal links. One thorough sentence per link is the target. Do not repeat the same point in different words."
    }
  },
  "palate_element_detect": {
    "acidez": [
      "acidez",
      "ácida",
      "acida"
    ],
    "alcohol": [
      "alcohol"
    ],
    "características del sabor": [
      "sabor",
      "fruta",
      "notas"
    ],
    "cuerpo": [
      "cuerpo"
    ],
    "dulzor": [
      "dulzor",
      "dulce",
      "seco",
      "semiseco"
    ],
    "final": [
      "final",
      "persistencia"
    ],
    "intensidad del sabor": [
      "intensidad"
    ],
    "tanino": [
      "tanino",
      "táni",
      "tani"
    ]
  },
  "quality_principle": "Quality level must be justified by specific tasting observations. It is NOT an opinion — it must follow from evidence.",
  "quality_terms": [
    "defectuoso",
    "pobre",
    "aceptable",
    "bueno",
    "muy bueno",
    "excelente"
  ],
  "readiness_terms": [
    "demasiado joven",
    "se puede beber ahora, pero tiene potencial para el envejecimiento",
    "beber ahora: no adecuado para el envejecimiento o para un mayor envejecimiento",
    "demasiado viejo"
  ],
  "sat_sections": [
    {
      "detect": [
        "aspecto",
        "apariencia",
        "vista",
        "appearance"
      ],
      "elements": [
        "claridad",
        "intensidad",
        "color",
        "otras observaciones"
      ],
      "id": "aspecto",
      "label": "aspecto",
      "section": "appearance"
    },
    {
      "detect": [
        "nariz",
        "nose",
        "aroma"
      ],
      "elements": [
        "condición",
        "intensidad",
        "características del aroma",
        "evolución"
      ],
      "id": "nariz",
      "label": "nariz",
      "section": "nose"
    },
    {
      "detect": [
        "boca",
        "paladar",
        "palate"
      ],
      "elements": [
        "dulzor",
        "acidez",
        "tanino",
        "alcohol",
        "cuerpo",
        "burbuja",
        "intensidad del sabor",
        "características del sabor",
        "final"
      ],
      "id": "boca",
      "label": "boca",
      "section": "palate"
    },
    {
      "detect": [
        "conclusion",
        "conclusiones",
        "calidad",
        "quality"
      ],
      "elements": [
        "nivel de calidad",
        "estado para el consumo/potencial para el envejecimiento"
      ],
      "id": "conclusiones",
      "label": "conclusiones",
      "section": "conclusions"
    }
  ],
  "scales": {
    "appearance.clarity": [
      "claro",
      "turbio"
    ],
    "appearance.colour_red": [
      "púrpura",
      "rubí",
      "granate",
      "teja",
      "marrón"
    ],
    "appearance.colour_rose": [
      "rosado",
      "salmón",
      "naranja"
    ],
    "appearance.colour_white": [
      "verde limón",
      "amarillo limón",
      "dorado",
      "ámbar",
      "marrón"
    ],
    "appearance.intensity": [
      "pálida",
      "media",
      "profunda"
    ],
    "conclusions.quality_level": [
      "defectuoso",
      "pobre",
      "aceptable",
      "bueno",
      "muy bueno",
      "excelente"
    ],
    "conclusions.readiness_for_drinking": [
      "demasiado joven",
      "se puede beber ahora, pero tiene potencial para el envejecimiento",
      "beber ahora: no adecuado para el envejecimiento o para un mayor envejecimiento",
      "demasiado viejo"
    ],
    "nose.condition": [
      "limpia",
      "no limpia"
    ],
    "nose.development": [
      "joven",
      "en evolución",
      "evolucionado",
      "cansado/pasó su mejor momento"
    ],
    "nose.intensity": [
      "ligera",
      "media(-)",
      "media",
      "media(+)",
      "pronunciada"
    ],
    "palate.acidity": [
      "baja",
      "media(-)",
      "media",
      "media(+)",
      "alta"
    ],
    "palate.alcohol": [
      "bajo",
      "medio",
      "alto"
    ],
    "palate.body": [
      "poco",
      "medio(-)",
      "medio",
      "medio(+)",
      "mucho"
    ],
    "palate.finish": [
      "corto",
      "medio(-)",
      "medio",
      "medio(+)",
      "largo"
    ],
    "palate.flavour_intensity": [
      "ligera",
      "media(-)",
      "media",
      "media(+)",
      "pronunciada"
    ],
    "palate.mousse": [
      "delicada",
      "cremosa",
      "agresiva"
    ],
    "palate.sweetness": [
      "seco",
      "casi seco",
      "semiseco",
      "semidulce",
      "dulce",
      "muy dulce"
    ],
    "palate.tannin": [
      "bajo",
      "medio(-)",
      "medio",
      "medio(+)",
      "alto"
    ]
  },
  "schema_version": "distinction_coach_v1",
  "simple_wine_note": "Para vinos simples, indicar 'simple' es la observación correcta. No inventes aromas terciarios: en la clave oficial, declarar SIMPLE es lo que corresponde y los aromas primarios válidos completan la nota.",
  "source": "Phase X.1 assessment-intelligence assets (compiled)"
};
