// Generated by tools/question_generation/distinction_coach_exporter.py
// Compiled from knowledge/ assessment-intelligence assets. Do not edit.
// Learner-facing strings are Spanish by contract (Phase Z.2 localization guard).
// Formative guidance only. safe_for_examiner=false.
window.DISTINCTION_COACH = {
  "command_verbs": {
    "assess": {
      "definition": "Emite un juicio fundamentado sobre el valor, la calidad o la relevancia de algo, basándote en criterios establecidos.",
      "do": [
        "Declara un juicio claro",
        "Apóyalo con evidencia específica de cata o de región",
        "Usa criterios WSET apropiados"
      ],
      "do_not": [
        "Dar una opinión sin respaldo",
        "Enumerar observaciones sin conclusión"
      ],
      "mentor_hint": "Empieza por tu juicio («Este vino es de calidad excelente») y aporta de inmediato 3 o más observaciones específicas que lo respalden. No dejes la conclusión para el final."
    },
    "compare": {
      "definition": "Identifica semejanzas y diferencias entre dos o más elementos. Se esperan semejanzas Y diferencias salvo que se indique lo contrario.",
      "do": [
        "Aborda semejanzas y diferencias",
        "Usa estructura paralela para mayor claridad",
        "Cubre varias dimensiones"
      ],
      "do_not": [
        "Describir cada elemento por separado sin vincularlos",
        "Cubrir solo un elemento en detalle"
      ],
      "mentor_hint": "Organiza por dimensión: «En cuanto al clima, X es [fresco/cálido] mientras que Y es [fresco/cálido]…». No escribas un ensayo sobre X y luego otro sobre Y."
    },
    "describe": {
      "definition": "Enuncia las características, rasgos o apariencia de algo. No expliques causas ni razones.",
      "do": [
        "Nombra características",
        "Usa vocabulario SAT (en preguntas de cata)",
        "Sé específico/a",
        "Cubre todas las dimensiones relevantes"
      ],
      "do_not": [
        "Explicar por qué",
        "Dar opiniones",
        "Comparar con otros ejemplos",
        "Añadir causas o mecanismos"
      ],
      "mentor_hint": "Responde solo al «qué». Si te sorprendes escribiendo «porque» o «esto significa», estás explicando, no describiendo."
    },
    "evaluate": {
      "definition": "Emite un juicio fundamentado, sopesando la relevancia de la evidencia. Suele implicar una consideración más amplia o matizada que «assess».",
      "do": [
        "Sopesa varias piezas de evidencia",
        "Declara una conclusión clara",
        "Reconoce la complejidad cuando sea relevante"
      ],
      "do_not": [
        "Limitarte a enumerar hechos (eso es describir)",
        "Dar opinión sin evidencia"
      ],
      "mentor_hint": "Piensa en «evaluar» como «explicar + juzgar»: explica los factores clave y luego indica cuál consideras más significativo y por qué."
    },
    "explain": {
      "definition": "Da razones o justifica un hecho, fenómeno o resultado. Debe incluir una relación causa-efecto.",
      "do": [
        "Indica la causa",
        "Indica el mecanismo o proceso",
        "Indica el resultado o efecto",
        "Usa vocabulario técnico WSET"
      ],
      "do_not": [
        "Limitarte a nombrar o enumerar (eso es describir, no explicar)",
        "Dar afirmaciones sin respaldo"
      ],
      "mentor_hint": "Usa la estructura: [Factor] → [mecanismo] → [resultado en el vino]. Por ejemplo: «Temperaturas frescas ralentizan la maduración → menos acumulación de azúcar y más ácido málico retenido → mayor acidez en el vino final»."
    },
    "justify": {
      "definition": "Da razones o evidencia que respalden una posición o elección dada. La posición ya está planteada; debes defenderla.",
      "do": [
        "Selecciona la evidencia más sólida y específica",
        "Vincula la evidencia directamente con la posición",
        "Usa vocabulario WSET"
      ],
      "do_not": [
        "Argumentar en contra de la posición",
        "Dar descripciones genéricas sin relación con la afirmación"
      ],
      "mentor_hint": "Empieza reformulando la posición en una línea y da 3 o más razones específicas. Cada razón debe conectar directamente con la afirmación."
    }
  },
  "common_quality_errors": [
    "Elegir «excelente» para un vino simple porque gusta personalmente",
    "No reconocer «simple» como descriptor válido que obtiene marcas en vinos básicos",
    "Elegir «muy bueno» para un vino con solo aromas primarios (debería ser «bueno» o «aceptable»)",
    "Elegir «bueno» cuando el vino muestra claramente las tres categorías de aroma y final largo (debería ser «muy bueno» o «excelente»)"
  ],
  "governance": {
    "examiner_scoring_allowed": false,
    "formative_only": true,
    "safe_for_examiner": false,
    "uses_api": false,
    "uses_llm": false
  },
  "justification_connectors": [
    "porque",
    "ya que",
    "debido",
    "por lo tanto",
    "esto indica",
    "se debe a",
    "lo que sugiere"
  ],
  "mentor_hints": {
    "MCQ_strategy": {
      "common_errors": [
        "Sobrepensar los distractores",
        "Elegir respuestas parcialmente correctas"
      ],
      "hint": "En preguntas SBA, elimina primero las opciones claramente incorrectas. La respuesta correcta es totalmente precisa, no parcialmente. WSET usa vocabulario preciso: «seco» no es lo mismo que «semiseco»."
    },
    "SAT_appearance": {
      "common_errors": [
        "Olvidar evaluar la limpidez",
        "Usar vocabulario no SAT (p. ej. «bonito», «oscuro»)"
      ],
      "hint": "Recorre el Aspecto en orden: limpidez → intensidad → color. Cada elemento tiene su propia escala. El color debe corresponder al tipo de vino (blanco, rosado, tinto)."
    },
    "SAT_nose": {
      "common_errors": [
        "Mezclar primarios/secundarios/terciarios sin asignar categorías",
        "Enumerar «fruta» genérica sin especificar"
      ],
      "hint": "Tras indicar condición (limpio/defectuoso) e intensidad, identifica aromas por categoría: primarios (fruta, floral, vegetal), secundarios (roble, maloláctica, levadura), terciarios (crianza en botella, oxidación). Al menos un descriptor específico por categoría obtiene la marca."
    },
    "SAT_palate": {
      "common_errors": [
        "Omitir la evaluación de acidez o tanino",
        "Tratar el «cuerpo» como un sabor y no como elemento estructural",
        "Confundir las escalas del final de boca"
      ],
      "hint": "En boca, cubre los nueve elementos en orden: dulzor, acidez, tanino (solo tintos), alcohol, cuerpo, intensidad de sabor, características de sabor, final. Cuerpo y final son conclusiones estructurales, no sabores."
    },
    "SAT_quality": {
      "common_errors": [
        "Elegir el nivel de calidad sin justificarlo con la nota de cata",
        "Usar «excelente» en vinos sin complejidad terciaria"
      ],
      "hint": "El nivel de calidad debe ser coherente con tu nota de cata. «Excelente» requiere: intensidad pronunciada + las tres categorías de aroma + equilibrio + final largo. Un vino simple no puede ser excelente."
    },
    "SAT_readiness": {
      "common_errors": [
        "No alinear el estado de consumo con la etapa de evolución",
        "Elegir «demasiado joven» para un vino en evolución"
      ],
      "hint": "«Puede beberse ahora pero tiene potencial» es la respuesta correcta para la mayoría de vinos premium con complejidad en desarrollo. Elige «demasiado joven» solo si el vino está claramente sin resolver (tanino sin integrar, sin evolución)."
    },
    "short_answer_structure": {
      "common_errors": [
        "Dar una sola razón en una pregunta de varias marcas",
        "Explicar sin especificar la causa"
      ],
      "hint": "Cuenta las marcas. Una pregunta de explicar de 4 marcas necesita 4 vínculos causales distintos. El objetivo es una oración completa por vínculo. No repitas el mismo punto con otras palabras."
    }
  },
  "palate_element_detect": {
    "acidez": [
      "acidez",
      "ácida",
      "acida"
    ],
    "alcohol": [
      "alcohol"
    ],
    "características del sabor": [
      "sabor",
      "fruta",
      "notas"
    ],
    "cuerpo": [
      "cuerpo"
    ],
    "dulzor": [
      "dulzor",
      "dulce",
      "seco",
      "semiseco"
    ],
    "final": [
      "final",
      "persistencia"
    ],
    "intensidad del sabor": [
      "intensidad"
    ],
    "tanino": [
      "tanino",
      "táni",
      "tani"
    ]
  },
  "quality_principle": "El nivel de calidad debe justificarse con observaciones específicas de la cata. NO es una opinión: debe derivarse de la evidencia.",
  "quality_terms": [
    "defectuoso",
    "pobre",
    "aceptable",
    "bueno",
    "muy bueno",
    "excelente"
  ],
  "readiness_terms": [
    "demasiado joven",
    "se puede beber ahora, pero tiene potencial para el envejecimiento",
    "beber ahora: no adecuado para el envejecimiento o para un mayor envejecimiento",
    "demasiado viejo"
  ],
  "sat_sections": [
    {
      "detect": [
        "aspecto",
        "apariencia",
        "vista",
        "appearance"
      ],
      "elements": [
        "claridad",
        "intensidad",
        "color",
        "otras observaciones"
      ],
      "id": "aspecto",
      "label": "aspecto",
      "section": "appearance"
    },
    {
      "detect": [
        "nariz",
        "nose",
        "aroma"
      ],
      "elements": [
        "condición",
        "intensidad",
        "características del aroma",
        "evolución"
      ],
      "id": "nariz",
      "label": "nariz",
      "section": "nose"
    },
    {
      "detect": [
        "boca",
        "paladar",
        "palate"
      ],
      "elements": [
        "dulzor",
        "acidez",
        "tanino",
        "alcohol",
        "cuerpo",
        "burbuja",
        "intensidad del sabor",
        "características del sabor",
        "final"
      ],
      "id": "boca",
      "label": "boca",
      "section": "palate"
    },
    {
      "detect": [
        "conclusion",
        "conclusiones",
        "calidad",
        "quality"
      ],
      "elements": [
        "nivel de calidad",
        "estado para el consumo/potencial para el envejecimiento"
      ],
      "id": "conclusiones",
      "label": "conclusiones",
      "section": "conclusions"
    }
  ],
  "scales": {
    "appearance.clarity": [
      "claro",
      "turbio"
    ],
    "appearance.colour_red": [
      "púrpura",
      "rubí",
      "granate",
      "teja",
      "marrón"
    ],
    "appearance.colour_rose": [
      "rosado",
      "salmón",
      "naranja"
    ],
    "appearance.colour_white": [
      "verde limón",
      "amarillo limón",
      "dorado",
      "ámbar",
      "marrón"
    ],
    "appearance.intensity": [
      "pálida",
      "media",
      "profunda"
    ],
    "conclusions.quality_level": [
      "defectuoso",
      "pobre",
      "aceptable",
      "bueno",
      "muy bueno",
      "excelente"
    ],
    "conclusions.readiness_for_drinking": [
      "demasiado joven",
      "se puede beber ahora, pero tiene potencial para el envejecimiento",
      "beber ahora: no adecuado para el envejecimiento o para un mayor envejecimiento",
      "demasiado viejo"
    ],
    "nose.condition": [
      "limpia",
      "no limpia"
    ],
    "nose.development": [
      "joven",
      "en evolución",
      "evolucionado",
      "cansado/pasó su mejor momento"
    ],
    "nose.intensity": [
      "ligera",
      "media(-)",
      "media",
      "media(+)",
      "pronunciada"
    ],
    "palate.acidity": [
      "baja",
      "media(-)",
      "media",
      "media(+)",
      "alta"
    ],
    "palate.alcohol": [
      "bajo",
      "medio",
      "alto"
    ],
    "palate.body": [
      "poco",
      "medio(-)",
      "medio",
      "medio(+)",
      "mucho"
    ],
    "palate.finish": [
      "corto",
      "medio(-)",
      "medio",
      "medio(+)",
      "largo"
    ],
    "palate.flavour_intensity": [
      "ligera",
      "media(-)",
      "media",
      "media(+)",
      "pronunciada"
    ],
    "palate.mousse": [
      "delicada",
      "cremosa",
      "agresiva"
    ],
    "palate.sweetness": [
      "seco",
      "casi seco",
      "semiseco",
      "semidulce",
      "dulce",
      "muy dulce"
    ],
    "palate.tannin": [
      "bajo",
      "medio(-)",
      "medio",
      "medio(+)",
      "alto"
    ]
  },
  "schema_version": "distinction_coach_v1",
  "simple_wine_note": "Para vinos simples, indicar 'simple' es la observación correcta. No inventes aromas terciarios: en la clave oficial, declarar SIMPLE es lo que corresponde y los aromas primarios válidos completan la nota.",
  "source": "Phase X.1 assessment-intelligence assets (compiled)"
};
