import { authenticatedLabUser, LAB_CORS, labJson, recordLabEpistemicEvent, responseVersion, stateForStep, validStepKind } from '../_shared/lab-runtime.ts';
import { evaluateBottleResponse } from '../_shared/bottle-evaluation.ts';
import { selectBottleMentor } from '../_shared/bottle-mentor.ts';

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: LAB_CORS });
  const auth = await authenticatedLabUser(req, 'bottle_lab');
  if (auth.response) return auth.response;
  const { supabase, user } = auth;
  try {
    const body = await req.json().catch(() => null);
    const sessionId = typeof body?.session_id === 'string' ? body.session_id : '';
    const key = typeof body?.idempotency_key === 'string' ? body.idempotency_key.trim() : '';
    const stepKey = typeof body?.step_key === 'string' ? body.step_key.trim() : '';
    const answer = body?.answer && typeof body.answer === 'object' && !Array.isArray(body.answer) ? body.answer : null;
    if (!sessionId || !key || key.length > 128 || !stepKey || !validStepKind(body?.step_kind) || !answer) return labJson({ ok: false, error: 'Invalid step' }, 400);
    const { data: session } = await supabase.from('lab_sessions').select('id,assignment_id,item_id,state,current_step,observations,hypotheses,confidence,idempotency_keys').eq('id', sessionId).eq('user_id', user.id).maybeSingle();
    if (!session) return labJson({ ok: false, error: 'Session not found' }, 404);
    const { data: assignment } = await supabase.from('lab_assignments').select('id,expires_at').eq('id', session.assignment_id).eq('user_id', user.id).maybeSingle();
    if (!assignment || new Date(assignment.expires_at).getTime() <= Date.now()) return labJson({ ok: false, error: 'Assignment expired' }, 409);
    if (['completed', 'abandoned', 'expired'].includes(session.state)) return labJson({ ok: false, error: 'Session is closed' }, 409);
    const oldKeys = Array.isArray(session.idempotency_keys) ? session.idempotency_keys : [];
    const replay = oldKeys.find((entry: any) => entry?.key === key);
    if (replay) return labJson({ ok: true, replay: true, state: replay.state, evaluation: replay.evaluation, step: replay.step });
    if (session.current_step !== stepKey) return labJson({ ok: false, error: 'Step is not active' }, 409);
    const { data: item } = await supabase.from('lab_items').select('public_content,evaluation_spec,evaluation_version').eq('item_id', session.item_id).eq('lab_type', 'bottle').eq('is_active', true).maybeSingle();
    if (!item) return labJson({ ok: false, error: 'Item unavailable' }, 404);
    const step = (item.public_content.steps || []).find((candidate: any) => candidate.id === stepKey);
    if (!step || step.kind !== body.step_kind) return labJson({ ok: false, error: 'Invalid active step' }, 409);
    const evaluation = evaluateBottleResponse(item.evaluation_spec || {}, { ...answer, kind: body.step_kind });
    const mentor = selectBottleMentor(item.evaluation_spec || {}, evaluation.mentor, `${session.id}:${key}`);
    evaluation.mentor_feedback = mentor;
    const steps = item.public_content.steps || [];
    const index = steps.findIndex((candidate: any) => candidate.id === stepKey);
    const next = steps[index + 1] || null;
    const nextState = stateForStep(step, !next);
    const now = new Date().toISOString();
    const response = { key, step_key: stepKey, step_kind: body.step_kind, version: responseVersion([...(session.observations || []), ...(session.hypotheses || [])], stepKey), answer, submitted_at: now };
    const observations = body.step_kind === 'observation' || body.step_kind === 'classification' ? [...(session.observations || []), response] : session.observations || [];
    const hypotheses = body.step_kind === 'hypothesis' ? [...(session.hypotheses || []), response] : session.hypotheses || [];
    const confidence = answer.confidence ? [...(session.confidence || []), { step_key: stepKey, value: answer.confidence, recorded_at: now }] : session.confidence || [];
    const publicStep = next ? { id: next.id, kind: next.kind, prompt: next.prompt, options: next.options || [], evidence: next.evidence || null } : null;
    const keys = [...oldKeys, { key, step_key: stepKey, state: nextState, evaluation, step: publicStep }];
    const updated = await supabase.from('lab_sessions').update({ state: nextState, current_step: next?.id || null, observations, hypotheses, confidence, idempotency_keys: keys, completed_at: nextState === 'reveal_available' ? now : null, updated_at: now }).eq('id', session.id).eq('user_id', user.id).eq('current_step', stepKey).select('id,state,current_step').single();
    if (updated.error || !updated.data) return labJson({ ok: false, error: 'Session changed; retry safely' }, 409);
    await supabase.from('lab_assignments').update({ status: nextState, completed_at: nextState === 'reveal_available' ? now : null }).eq('id', assignment.id).eq('user_id', user.id);
    await supabase.from('lab_evaluations').upsert({ session_id: session.id, response_key: key, evaluation_version: item.evaluation_version, result: evaluation }, { onConflict: 'session_id,response_key' });
    if (body.step_kind === 'hypothesis') await recordLabEpistemicEvent(supabase, { userId: user.id, sessionId: session.id, occurredAt: now, sourceMode: 'bottle_lab_pro', eventId: `bottle:${session.id}:${key}:decision`, eventType: 'decision_made', payload: { item_id: session.item_id, step_key: stepKey, result_band: evaluation.result.band }, evidence: { selected: evaluation.evidence.selected, ignored: evaluation.evidence.ignored }, metadata: { evaluation_version: item.evaluation_version, bias: evaluation.bias } });
    return labJson({ ok: true, replay: false, state: nextState, evaluation, step: publicStep });
  } catch { return labJson({ ok: false, error: 'Unable to submit Bottle Lab step' }, 500); }
});
